### PR TITLE
R9MM OTA

### PR DESCRIPTION
**Pull request by eMapleLuke**
Can I use my R9MM OTA and can I falsh it over the air?

### CODE REVIEW

**Comment by cruwaller** [comment]
should this be an issue?

**Comment by AlessandroAU** [comment]
No OTA is not yet supported, did you mean to make this a PR?

**Comment by eMapleLuke** [comment]
Ok, but will it work with the R9MM?

**Comment by JyeSmith** [comment]
Should work no problems.

**Pull request closed without merging**
