### PR TITLE
always sendLinkStatisticsToFC

### PR DESCRIPTION
**Pull request by JyeSmith**
Great for seeing what the rx is up to when cycling through rf modes.

### CODE REVIEW

**Comment by wvarty** [comment]
@JyeSmith this looks clean. Has it been tested?

**Comment by JyeSmith** [comment]
@wvarty All day yesterday by Sandro and I. No probs.

**Comment by wvarty** [comment]
You were both flying this one?

This change is pretty low risk. I'd be happy to merge. We need to do better in terms of testing with other PRs though :|

**Comment by wvarty** [comment]
Sorry! Wrong button!

**Pull request merged**
