### PR TITLE
Update R9M Lite Pro Targets.h

### PR DESCRIPTION
**Pull request by Jahnkeanater**
SWR Measurement still needs work.

### CODE REVIEW

**Comment by Jahnkeanater** [comment]
I messed up and used the same name twice #define GPIO_PIN_VRF2
The PA0 pin should probably be #define GPIO_PIN_SWR

**Comment by AlessandroAU** [comment]
Let's merge this in and go from there :) I can do some testing.

**Comment by Jahnkeanater** [comment]
#define GPIO_PIN_LED_RED is also used twice lol.

**Comment by mavericm1** [comment]
I was doing testing with @cruwaller and flashing bootloader and couldn't get it to work.  When looking at rc rx/tx  which are defined as PB11 and PB10, Package pins 21/22.   I do not see traces on the PCB for these pins and i do not believe they are used.

**Comment by mavericm1** [comment]
the pin marked on the left side in this image goes to the sport inverter i'm not sure if it is rx or tx.

image

**Comment by Jahnkeanater** [comment]
> 
> 
> the pin marked on the left side in this image goes to the sport inverter i'm not sure if it is rx or tx.
> 

Those 2 pins go to the RF switch 26SU on the other side of the board not the inverter.

**Comment by Jahnkeanater** [comment]
> 
> 
> R9Lite PRO target. I was doing testing with @cruwaller and flashing bootloader and couldn't get it to work. When looking at rc rx/tx which are defined as PB11 and PB10, Package pins 21/22. I do not see traces on the PCB for these pins and i do not believe they are used.
> 

The traces are underneath the STM32F303 Chip. There is are vias that bring them to the TI SN74LVC2G240 Dual Buffer Driver.

MCU Side


MINI JR

**Pull request merged**
