### PR TITLE
Fix: reverse lua buttons

### PR DESCRIPTION
**Pull request by JyeSmith**
Needs test by someone with an x9

### CODE REVIEW

**Comment by SpencerGraffunder** [comment]
The buttons are still wrong for moving between vars but it’s right when setting the value.

**Comment by JyeSmith** [comment]
@SpencerGraffunder can you please test again.

**Comment by SpencerGraffunder** [comment]
Now the cursor just goes off the top of the screen. Won't move down at all.

**Comment by SpencerGraffunder** [comment]
Up and down are working now. Can't move the cursor to the 'web server' though.

**Comment by JyeSmith** [comment]
Thanks.  Ill clean this up later before merging.

Selecting the web server isnt an option.  Ill comment it out later to avoid confusion and it can be added back when the functionality has been added.

**Pull request merged**
