### PR TITLE
Cleanup envs

### PR DESCRIPTION
**Pull request by AlessandroAU**
Reordered/renamed env to make a bit more sense.

Open for comments 
image

### CODE REVIEW

**Comment by JyeSmith** [comment]
I really liked the idea you had with the brackets.  Now that 2.4 is in the mix could the brackets be for 'FrSky Gear' then '900MHz' and '2.4GHz'.

**Comment by maybenikhil** [comment]
@JyeSmith To be consistent with how the wiki has been written (although it could be changed), I think it could make more sense to have either a double deep bracket OR do: `Off The Shelf Hardware` (split into FrSky and TTGO), and `DIY Hardware` (which could be split into 2.4Ghz), and subsection each of those into TX and RX

**Comment by AlessandroAU** [comment]
Turns out I can't use fancy characters in the env name or it break builds. What about this 
image

**Comment by maybenikhil** [comment]
img

how about this?(ill PR if needed) + I added the r9mx envs

**Comment by JyeSmith** [comment]
> 
> 
> Turns out I can't use fancy characters in the env name or it break builds. What about this
> image

@AlessandroAU I like this.  It matches the way I look for targets e.g. freq - rx/tx - hardware - upload method.  I would also bring the TTGO targets in to the DIY_900_TX category. 

@maybenikhil raises a point.  ExLRS works on the 2019 r9m so we can remove the 2018 to remove any confusion.  I dont think all FC firmware supports passthrough so we should specify BF for now.

**Comment by JBKingdon** [comment]
Do we still need the ttgo v1 target? As far as I can see v1 and v2 only differ by the pins for the oled which we don't use yet, plus we probably want to encourage people to use v2 over v1.

**Comment by JyeSmith** [comment]
Im happy to remove the v1 so it stops other from using it.  BUUUUT Sandro and I do still use it for bench top testing, so maybe leave.

**Comment by maybenikhil** [comment]
>@maybenikhil raises a point. ExLRS works on the 2019 r9m so we can remove the 2018 to remove any confusion. I dont think all FC firmware supports passthrough so we should specify BF for now.

@JyeSmith This was talked about on the discord, and inav, BF and emuf (the main FC firmware, besides flightone/falcox) all have passthrough capabilities.

**Pull request merged**
