### PR TITLE
ESP Backpack logger improvements

### PR DESCRIPTION
**Pull request by cruwaller**
Backpack logger to support 
* STK500 for `.elrs` files, DFU for `.bin` files.
* DFU upload to support flash start address

~~Bootloader v0.5.2 (R9M):~~
~~* STK500 only (FrSky dropped)~~
~~* Bootloader checks two different UART for upload (S.Port + PA9/PA10)~~

~~Platformio.ini clean up.~~

### CODE REVIEW

**Comment by cruwaller** [comment]
Dont merge this. Needs more testing...

**Comment by NiklasVoigt** [comment]
Test with R9M2018 stock bootloader succeed! 
Flash back to FrSky frimware also! 
Wifi target tested also!

**Comment by dimitroffs** [comment]
I also checked the branch - flashes okay both bootloader and firmware! Attaching the testing log for reference:

`BEGIN LOG2020-12-07T17:43:26.443Z Filesystem: used: 0 / free: 128261
2020-12-07T17:43:26.444Z Uploading file: r9m_bootloader.bin
2020-12-07T17:43:26.484Z Uploaded: 2048 bytes
2020-12-07T17:43:26.583Z Uploaded: 4096 bytes
2020-12-07T17:43:26.686Z Uploaded: 6140 bytes
2020-12-07T17:43:26.688Z Total uploaded size 6140 of 6140
2020-12-07T17:43:26.743Z Firmware Flash Requested!
2020-12-07T17:43:26.744Z   the firmware file: '/r9m_bootloader.bin'
2020-12-07T17:43:26.748Z filesize: 6140
2020-12-07T17:43:26.749Z Using flash base: 0x8000000
2020-12-07T17:43:27.402Z trying to init chip...
2020-12-07T17:43:27.403Z init chip succeeded.
2020-12-07T17:43:27.425Z Bootloader version: 0x22
2020-12-07T17:43:27.426Z Chip ID: 0x410
2020-12-07T17:43:27.427Z erasing pages: 0...6
2020-12-07T17:43:27.546Z erase Success!
2020-12-07T17:43:27.548Z begin to write file.
2020-12-07T17:43:28.284Z Write 83%
2020-12-07T17:43:28.436Z Write 100%
2020-12-07T17:43:28.455Z file write succeeded.
2020-12-07T17:43:28.456Z begin to verify file.
2020-12-07T17:43:29.078Z Verify 83%
2020-12-07T17:43:29.205Z Verify 100%
2020-12-07T17:43:29.221Z verify file succeeded.
2020-12-07T17:43:29.222Z start application.
2020-12-07T17:43:29.245Z Update Successful!
2020-12-07T17:45:54.211Z Filesystem: used: 0 / free: 128261
2020-12-07T17:45:54.213Z Uploading file: firmware.elrs
2020-12-07T17:45:54.248Z Uploaded: 2048 bytes
2020-12-07T17:45:54.346Z Uploaded: 4096 bytes
2020-12-07T17:45:54.373Z Uploaded: 6144 bytes
2020-12-07T17:45:54.470Z Uploaded: 8192 bytes
2020-12-07T17:45:54.568Z Uploaded: 10240 bytes
2020-12-07T17:45:54.597Z Uploaded: 12288 bytes
2020-12-07T17:45:54.692Z Uploaded: 14336 bytes
2020-12-07T17:45:54.787Z Uploaded: 16384 bytes
2020-12-07T17:45:54.813Z Uploaded: 18432 bytes
2020-12-07T17:45:54.914Z Uploaded: 20480 bytes
2020-12-07T17:45:54.955Z Uploaded: 22528 bytes
2020-12-07T17:45:55.046Z Uploaded: 24576 bytes
2020-12-07T17:45:55.149Z Uploaded: 26624 bytes
2020-12-07T17:45:55.176Z Uploaded: 28672 bytes
2020-12-07T17:45:55.272Z Uploaded: 30720 bytes
2020-12-07T17:45:55.375Z Uploaded: 32768 bytes
2020-12-07T17:45:55.399Z Uploaded: 34816 bytes
2020-12-07T17:45:55.472Z Uploaded: 36864 bytes
2020-12-07T17:45:55.501Z Uploaded: 38912 bytes
2020-12-07T17:45:55.581Z Uploaded: 40960 bytes
2020-12-07T17:45:55.675Z Uploaded: 43008 bytes
2020-12-07T17:45:55.702Z Uploaded: 45056 bytes
2020-12-07T17:45:55.762Z Uploaded: 45972 bytes
2020-12-07T17:45:55.765Z Total uploaded size 45972 of 45972
2020-12-07T17:45:55.832Z Firmware Flash Requested!
2020-12-07T17:45:55.836Z   the firmware file: '/firmware.elrs'
2020-12-07T17:45:55.839Z STK500: filesize: 45972
2020-12-07T17:45:55.987Z STK500: [ERROR] protocol failed...
2020-12-07T17:45:55.991Z STK500: waiting sync...
2020-12-07T17:45:55.998Z STK500: Sync OK
2020-12-07T17:45:55.999Z STK500: begin to write.
2020-12-07T17:45:56.725Z STK500: Write 11%
2020-12-07T17:45:57.487Z STK500: Write 22%
2020-12-07T17:45:58.233Z STK500: Write 33%
2020-12-07T17:45:58.984Z STK500: Write 44%
2020-12-07T17:45:59.735Z STK500: Write 55%
2020-12-07T17:46:00.492Z STK500: Write 66%
2020-12-07T17:46:01.244Z STK500: Write 77%
2020-12-07T17:46:02.001Z STK500: Write 88%
2020-12-07T17:46:02.761Z STK500: Write 100%
2020-12-07T17:46:02.764Z STK500: write succeeded.
2020-12-07T17:46:02.859Z Update Successful!
2020-12-07T17:46:07.112Z UART STATS Bad:Good = 0:240
2020-12-07T17:46:08.113Z UART STATS Bad:Good = 0:200
2020-12-07T17:46:09.114Z UART STATS Bad:Good = 0:200
2020-12-07T17:46:10.115Z UART STATS Bad:Good = 0:201
2020-12-07T17:46:11.116Z UART STATS Bad:Good = 0:200`

**Review by dimitroffs — APPROVED** [review]
We could apply check in future based on filename what address to use in new input field for 'flash_address'. Good job, Pete!

**Comment by cruwaller** [comment]
That error is printed because STK500 SYNC fails... Maybe it would be good to add a bit more info there :)

**Comment by NiklasVoigt** [comment]
any news?

**Comment by cruwaller** [comment]
This is tested to work so good to go :)

**Comment by cruwaller** [comment]
@AlessandroAU does this still need some changes or is this good to go?

**Comment by cruwaller** [comment]
This needs rework...

**Comment by AlessandroAU** [comment]
Sorry I left too long to test and it got out of date :|

**Comment by cruwaller** [comment]
PR rebased on top of latest master and bootloader stuff removed (committed already in #260 ).

I also added a simple filename validation before enabling the flash buttons.

**Comment by cruwaller** [comment]
@dimitroffs and @NiklasVoigt could you give try this updated version as well?

**Review by dimitroffs — APPROVED** [review]
Nice work, Pete! Looks okay for me. File checks are doing well, I was able to flash as before. We'll do styling/reworking the html at later point - maybe some wording could be improved (this is coming from my previous html style change). For me it is okay to be merged :)

**Comment by NiklasVoigt** [comment]
I've tested it too and looks good! Here is the log:

> 2021-01-03T22:44:17.174Z Filesystem: used: 0 / free: 128261
2021-01-03T22:44:17.188Z Uploading file: firmware.elrs
2021-01-03T22:44:17.410Z Uploaded: 2048 bytes
2021-01-03T22:44:17.582Z Uploaded: 4096 bytes
2021-01-03T22:44:17.606Z Uploaded: 6144 bytes
2021-01-03T22:44:17.778Z Uploaded: 8192 bytes
2021-01-03T22:44:17.830Z Uploaded: 10240 bytes
2021-01-03T22:44:17.970Z Uploaded: 12288 bytes
2021-01-03T22:44:18.146Z Uploaded: 14336 bytes
2021-01-03T22:44:18.194Z Uploaded: 16384 bytes
2021-01-03T22:44:18.338Z Uploaded: 18432 bytes
2021-01-03T22:44:18.391Z Uploaded: 20480 bytes
2021-01-03T22:44:18.547Z Uploaded: 22528 bytes
2021-01-03T22:44:18.702Z Uploaded: 24576 bytes
2021-01-03T22:44:18.758Z Uploaded: 26624 bytes
2021-01-03T22:44:18.931Z Uploaded: 28672 bytes
2021-01-03T22:44:19.082Z Uploaded: 30720 bytes
2021-01-03T22:44:19.134Z Uploaded: 32768 bytes
2021-01-03T22:44:19.290Z Uploaded: 34816 bytes
2021-01-03T22:44:19.339Z Uploaded: 36864 bytes
2021-01-03T22:44:19.503Z Uploaded: 38912 bytes
2021-01-03T22:44:19.630Z Uploaded: 40960 bytes
2021-01-03T22:44:19.702Z Uploaded: 43008 bytes
2021-01-03T22:44:19.854Z Uploaded: 45056 bytes
2021-01-03T22:44:19.968Z Uploaded: 45836 bytes
2021-01-03T22:44:19.986Z Total uploaded size 45836 of 45836
2021-01-03T22:44:20.035Z STM32 Firmware Flash Requested!
2021-01-03T22:44:20.050Z   the firmware file: '/firmware.elrs'
2021-01-03T22:44:20.067Z STK500: filesize: 45836
2021-01-03T22:44:20.146Z STK500: Waiting sync...
2021-01-03T22:44:20.194Z STK500: [ERROR] sync fail...
2021-01-03T22:44:20.209Z STK500: Waiting sync...
2021-01-03T22:44:20.242Z STK500: [ERROR] sync fail...
2021-01-03T22:44:20.258Z STK500: Waiting sync...
2021-01-03T22:44:20.272Z STK500: Sync OK
2021-01-03T22:44:20.288Z STK500: begin to write.
2021-01-03T22:44:20.991Z STK500: Write 11%
2021-01-03T22:44:21.734Z STK500: Write 22%
2021-01-03T22:44:22.498Z STK500: Write 33%
2021-01-03T22:44:23.251Z STK500: Write 44%
2021-01-03T22:44:24.006Z STK500: Write 55%
2021-01-03T22:44:24.774Z STK500: Write 66%
2021-01-03T22:44:25.519Z STK500: Write 77%
2021-01-03T22:44:26.274Z STK500: Write 89%
2021-01-03T22:44:27.014Z STK500: Write 100%
2021-01-03T22:44:27.032Z STK500: write succeeded.
2021-01-03T22:44:27.194Z Update Successful!
2021-01-03T22:44:27.221Z Wire.h begin()
2021-01-03T22:44:27.606Z 12
2021-01-03T22:44:27.652Z  found! (match by REG_VERSION == 0x12)
2021-01-03T22:44:27.666Z Setting ExpressLRS LoRa reg defaults
2021-01-03T22:44:27.683Z 1000
2021-01-03T22:44:27.698Z set rate
2021-01-03T22:44:27.715Z Setting ExpressLRS LoRa reg defaults
2021-01-03T22:44:27.731Z 1140
2021-01-03T22:44:27.744Z About to start CRSF task...
2021-01-03T22:44:27.758Z STM32 Platform Detected...
2021-01-03T22:44:27.776Z Start STM32 R9M TX CRSF UART
2021-01-03T22:44:27.790Z STM32 CRSF UART LISTEN TASK STARTED
2021-01-03T22:44:27.803Z CRSF UART Connected
2021-01-03T22:44:29.450Z UART STATS Bad:Good = 0:119
2021-01-03T22:44:30.463Z UART STATS Bad:Good = 0:100
2021-01-03T22:44:31.454Z UART STATS Bad:Good = 0:100

**Pull request merged**
