### PR TITLE
update to 8.0.0 ststm platform

### PR DESCRIPTION
**Pull request by AlessandroAU**

### CODE REVIEW

**Comment by AlessandroAU** [comment]
@JyeSmith @wvarty

**Comment by maybenikhil** [comment]
want me to test fly this?

**Comment by maybenikhil** [comment]
works well on my HW

**Comment by AlessandroAU** [comment]
Did you test r9mm and  r9m?

**Comment by maybenikhil** [comment]
yes

**Comment by AlessandroAU** [comment]
@JyeSmith why didn't yours work? :|

**Comment by JyeSmith** [comment]
@AlessandroAU PICNIC? or hardware issues.  I havent flow the r9 in a few weeks.

**Comment by R4ynor** [comment]
I tested yesterday on my r9m 2019 and r9mx (repositioned to avoid heat issue). 
Worked flawlessly.

**Comment by AlessandroAU** [comment]
Thanks guys :) good to know. Will merge after I do some test flights myself

**Comment by JyeSmith** [comment]
@AlessandroAU tested again on the bench and it connects fine.  NFI what was wrong before.

**Comment by AlessandroAU** [comment]
Awesome

**Pull request merged**
