### PR TITLE
Add support for R9MX target

### PR DESCRIPTION
**Pull request by R4ynor**
I added support for the R9MX target. There is some workaround to make it compile with the newer version of ststm32 platform (STM32_hwTimer.h and STM32_hwTimer.cpp).

Also there is a problem with the st-link bundled with PIO. It uses a very old version that doesn't support the MCU of the R9MX, so users will need to grab the last st-link utility and manually flash it or update the files in PIO.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Any reason not to use the older version the other targets use?

**Comment by AlessandroAU** [comment]
It doesn't support the cpu

**Comment by JyeSmith** [comment]
Well let's get this in and then look at updating all the targets.

**Comment by AlessandroAU** [comment]
We have to do it all at once because it requires changes to the stm32 hardwaretimer calls

**Comment by AlessandroAU** [comment]
Works :) we need to update and test all the other platforms on ststm7.2.0 at a later stage

**Pull request merged**
