### PR TITLE
lua: use virtual key events

### PR DESCRIPTION
**Pull request by snaewe**
This fixes the non-working movent on the X9D+

Signed-off-by: Stefan Naewe <stefan.naewe@gmail.com>

### CODE REVIEW

**Comment by dimitroffs** [comment]
tested on x9d+ with master-dev branch - works as it is expected!

**Review by dimitroffs — APPROVED** [review]

**Comment by dimitroffs** [comment]
after tweaking a little bit.. I noticed one side effect.. it works as it should on the main menu. But when I try to change one of the possible options (packet rate, tlm ratio, power) I sometimes see the exact change, sometimes - I don't. When I press enter - value is correctly set, but it is not refreshed while changing.. will continue testing it, but maybe some refresh of selected value logic should be changed on the lua itself.

**Comment by JyeSmith** [comment]
Working on the qx7.

The up/down is reversed to before but I dont see that as a big issue on scroll wheels.  I think its more important for handsets with up/down buttons to be correct.

**Comment by JyeSmith** [comment]
@dimitroffs The jerking changes could be due to all the writes from lua to the module.  This should be fixed with the other PR merging Pehos version.

**Review by JyeSmith — APPROVED** [review]

**Comment by wvarty** [comment]
Tested and working as expected on Jumper T16.
Scroll wheel is still reversed when changing values, but AFAIK that's a different issue.

**Pull request merged**
