### PR TITLE
Adds r9 868Mhz as a Rx

### PR DESCRIPTION
**Pull request by pierrotm777**
Hello,

Wonderful job, really.
I have a R9 868Mhz receiver ACCST EU LBT version.
Do you think that shall be possible to upload your firmware in future ?

Thanks

Pierre

### CODE REVIEW

**Comment by AlessandroAU** [comment]
You can already use that receiver as an RX, do you want to use it an TX?

**Comment by pierrotm777** [comment]
Your question is if i want to use my R9 receiver as TX ?

**Comment by AlessandroAU** [comment]
Yes, why did you comment on this PR?

Your RX already works and is supported.

**Comment by JyeSmith** [comment]
@pierrotm777 your rx should flash no problems.

https://github.com/AlessandroAU/ExpressLRS/wiki/Flashing-ExpressLRS#target-frsky-r9-mini-or-r9mm

**Pull request closed without merging**
