### PR TITLE
EU 868/433MHz additions

### PR DESCRIPTION
**Pull request by dabit20**
- Frequency tables were added for the EU unlicensed spectrum.
- The code is FHSS.cpp/FHSS.h was modified to calculate the number of FHSS frequencies at compile time instead of using #ifdefs and hard coded numbers. This makes creating additional frequency bands much easier.
- rx_main.cpp/tx_main.cpp are changed to accomodate the additional _EU frequency bands.
- By default no regulatory domain is defined in common.h. This produces an 'No regulatory domain defined, please define one in common.h' error at compile time and forces users to select one matching their region.

- Not related to the EU bands, but a bugfix: There was an error in the PlatformIO.ini file; the build target for R9MM_R9MINI_RX_STM32F301_BetaflightPassthrough was trying to take settings from the R9MM_RX_STM32F301_STLINK target. This is incorrect; it should point to R9MM_R9MINI_RX_STM32F301_STLINK.

The code has been tested on an R9M/R9MM combination. To check if the code would also work with a very limited number of center frequencies (as is the case with 433MHz) a test was conducted with a 3-entry table. This worked well. 
No tests have been performed with Espressif-based platforms, but it is unlikely that this PR breaks those targets.

### CODE REVIEW

**Comment by wvarty** [comment]
Looks really good @dabit20 !

**Comment by JyeSmith** [comment]
@wvarty have you tested 915? If not, I can in a couple of days.

@AlessandroAU are you going to bother to test 433?

**Comment by wvarty** [comment]
@JyeSmith haven’t tested 915 on this branch.

**Comment by dabit20** [comment]
For what it's worth: I 'emulated' 433MHz by simply using three 868MHz frequencies and forcing SX1276. I also checked visually that the correct code paths were taken when the #defines are changed (VSCode shows visually whether an #ifdef is active or not)

**Comment by gretel** [comment]
#49

**Comment by MykhailoVyn** [comment]
@dabit20
@pkendall64
@bkleiner 
Hi, is it possible to use wider Frequency hopping tables on the same hardware, provided that I have permission to use those frequencies?

**Pull request merged**
