### PR TITLE
GPLv3 License

### PR DESCRIPTION
**Pull request by brandonrc**

### CODE REVIEW

**Review by cruwaller — APPROVED** [review]

**Comment by brandonrc** [comment]
CC @JyeSmith @wvarty @P-I-Engineer @maybenikhil @R4ynor @JamesKingdon 

What y'all think?

**Review by maybenikhil — APPROVED** [review]

**Comment by JBKingdon** [comment]
Just referencing the associated issue for completeness: https://github.com/AlessandroAU/ExpressLRS/issues/95

The guidelines suggest the file containing the license be called "COPYING" - does it make sense to stick with the convention or does it not matter?

https://choosealicense.com/licenses/gpl-3.0/

I have no objections to the project adopting the gpl3 license.

**Comment by JyeSmith** [comment]
Boooo

... looks fine :)

**Review by JyeSmith — APPROVED** [review]

**Review by R4ynor — APPROVED** [review]

**Review by octalmage — APPROVED** [review]

**Comment by JyeSmith** [comment]
@brandonrc it makes more sense to leave the file named LICENSE.

**Comment by brandonrc** [comment]
@JyeSmith I was looking at other GPLv3 projects and they used COPYING.TXT

**Comment by brandonrc** [comment]
@JyeSmith can you merge this 🤣 

I do not have the power.

**Comment by JyeSmith** [comment]
I've added the license via the GitHub template.

Thanks for pushing this along @brandonrc :+1:

**Pull request closed without merging**
